apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: dGVzdHVzZXI=     #Nombre de usuario de la base de datos 'testuser'
 password: dGVzdHVzZXJAMTIz     #Contraseña del usuario de la db 'testuser@123'